import React from 'react'
import Link from 'next/link'
import Head from 'next/dist/shared/lib/head'

const about = () => {
    return (
        <div>
            <Head>
                <title>About | xyz</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <h1>About Page</h1>
            <Link href="/">
                Home 
            </Link>
        </div>
    )
}

export default about
