import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import commerce from '../lib/commerce'
import Link from 'next/link'

export default function Home({ categories, products }) {

  // console.log(categories)

  return (
    <div className={styles.container} style={{height: "fit-content"}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

    <Link href="/about">
      About
    </Link>
      {
        categories && categories.map(category => (
            <h1 key={category.id}> {category.name} </h1>
        ))
      }
      <br />
      {
        products && products.map(product => (
            <p key={product.id}>
               {product.name}
            </p>
        ))
      }
    
    </div>
  )
}


export async function getStaticProps() {
    
  const { data: categories } = await commerce.categories.list()
  const { data: products } = await commerce.products.list()

    return {
      props:{
        categories,
        products
      }
    }
}

