/* eslint-disable @next/next/link-passhref */
/* eslint-disable react/jsx-key */
/* eslint-disable @next/next/no-img-element */

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import commerce from '../lib/commerce'
import Link from 'next/link'

export default function Home({ categories, products }) {

  // console.log(categories)

  return (
    <div className={styles.container} style={{height: "fit-content"}} data-scroll data-scroll-section>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

    <Link href="/about">
      <h1> About</h1>
    </Link>
   
      {
        categories && categories.map(category => (
          <h1 key={category.id}> {category.name} </h1>
          ))
        }
      <br />
      {
        products && products.map(product => (
         <Link href={`/product/${product.permalink}`}>
          <div key={product.id}>            
              <p> {product.name} </p>
              <img 
                src={product.media.source} alt="image" style={{height:"100px"}} />
              <p>{product.price.formatted_with_symbol}</p>
              <br />
            </div>
         </Link>
        ))
      }
    
    </div>
  )
}


export async function getStaticProps() {
    
  const { data: categories } = await commerce.categories.list()
  const { data: products } = await commerce.products.list()

    return {
      props:{
        categories,
        products
      }
    }
}

